

directories:
    file_repo_root_directory: "/Users/michaelgeiser/files"
    files_to_check_directory: "/Users/michaelgeiser/filestocheck"
    new_files_directory: "/Users/michaelgeiser/filesnew"

behavior:
    delete_checked_file_if_dup: True
    copy_checked_file_if_new: True


mysql:
    host: localhost
    user: root
    passwd: my secret password
    db: write-math
other:
    preprocessing_queue:
        - preprocessing.scale_and_center
        - preprocessing.dot_reduction
        - preprocessing.connect_lines
    use_anonymous: yes